"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

import { useStore } from "@/components/StoreProvider";
import { errorMessage, formatMoney } from "@/lib/client-api";
import { localizedProductName, localizedVariantName } from "@/lib/i18n";

export default function CartPage() {
  const { user, cart, updateCartItem, removeCartItem, applyCoupon, removeCoupon, language } = useStore();
  const en = language === "en";
  const [message, setMessage] = useState("");
  async function coupon(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const code = String(new FormData(event.currentTarget).get("code")); try { await applyCoupon(code); setMessage(en ? "Coupon applied." : "تم تطبيق رمز الخصم."); } catch (error) { setMessage(errorMessage(error)); } }
  if (!user) return <main className="page container"><div className="empty-state"><h1>{en ? "Sign in to view your cart" : "سجّل الدخول لعرض سلتك"}</h1><Link className="primary-button" href="/login">{en ? "Sign in" : "تسجيل الدخول"}</Link></div></main>;
  if (!cart?.items.length) return <main className="page container"><div className="empty-state"><h1>{en ? "Your cart is empty" : "سلتك فارغة"}</h1><p>{en ? "Add products you love, then come back here." : "أضف منتجاتك المفضلة ثم عد إلى هنا."}</p><Link className="primary-button" href="/">{en ? "Continue shopping" : "متابعة التسوق"}</Link></div></main>;
  const money = (value: number) => formatMoney(value, cart.currency, language === "ar" ? "ar-SA" : "en-US");
  return <main className="page container"><div className="page-heading"><p className="eyebrow">{en ? "Review your items" : "راجع مشترياتك"}</p><h1>{en ? "Shopping cart" : "سلة التسوق"}</h1></div>{message && <div className={message.includes("تم") || message.includes("applied") ? "alert success" : "alert error"}>{message}</div>}<div className="cart-layout"><section className="panel">{cart.items.map((item) => { const image = item.product.images[0]?.url || item.product.image_url; const name = localizedProductName(item.product, language); return <article className="cart-item" key={item.id}><div className="cart-thumb" style={image ? { backgroundImage: `url(${image})` } : undefined}>{!image && name.slice(0,1)}</div><div><Link href={`/products/${item.product.slug}`}><h3>{name}</h3></Link><p>{localizedVariantName(item.variant, language)}</p><strong>{money(item.line_total_cents)}</strong></div><div><div className="quantity-control"><button aria-label={en ? "Decrease" : "تقليل"} disabled={item.quantity <= 1} onClick={() => void updateCartItem(item.id, item.quantity - 1)}>−</button><b>{item.quantity}</b><button aria-label={en ? "Increase" : "زيادة"} onClick={() => void updateCartItem(item.id, item.quantity + 1)}>+</button></div><button className="danger-button" onClick={() => void removeCartItem(item.id)}>{en ? "Remove" : "حذف"}</button></div></article>; })}</section><aside className="summary-card"><h2>{en ? "Order summary" : "ملخص الطلب"}</h2><div className="summary-line"><span>{en ? "Subtotal" : "المجموع"}</span><b>{money(cart.subtotal_cents)}</b></div><div className="summary-line"><span>{en ? "Discount" : "الخصم"}</span><b>− {money(cart.discount_cents)}</b></div><div className="summary-line"><span>{en ? "Tax" : "الضريبة"}</span><b>{money(cart.tax_cents)}</b></div><div className="summary-line"><span>{en ? "Shipping" : "الشحن"}</span><b>{cart.shipping_cents ? money(cart.shipping_cents) : (en ? "Free" : "مجاني")}</b></div><div className="summary-line total"><span>{en ? "Total" : "الإجمالي"}</span><b>{money(cart.total_cents)}</b></div>{cart.coupon_code ? <div className="alert success">{en ? "Code" : "الرمز"}: {cart.coupon_code} <button className="danger-button" onClick={() => void removeCoupon()}>{en ? "Remove" : "إزالة"}</button></div> : <form className="coupon-row" onSubmit={coupon}><input name="code" placeholder="WELCOME10" required/><button>{en ? "Apply" : "تطبيق"}</button></form>}<Link className="primary-button" href="/checkout">{en ? "Proceed to checkout" : "متابعة الدفع"}</Link></aside></div></main>;
}
