"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

import { useStore } from "@/components/StoreProvider";
import { apiRequest, errorMessage } from "@/lib/client-api";
import type { Address, Paginated } from "@/lib/types";

type Notification = { id:number; title:string; body:string; is_read:boolean; created_at:string };
export default function AccountPage(){
  const {user,language}=useStore(); const [addresses,setAddresses]=useState<Address[]>([]); const [notifications,setNotifications]=useState<Notification[]>([]); const [message,setMessage]=useState(""); const en=language==="en";
  async function load(){if(!user)return;const [addressPayload,notificationPayload]=await Promise.all([apiRequest<Address[]|Paginated<Address>>("/auth/addresses/"),apiRequest<Paginated<Notification>>("/notifications/")]);setAddresses(Array.isArray(addressPayload)?addressPayload:addressPayload.results);setNotifications(notificationPayload.results);}
  useEffect(()=>{void load();},[user]); // eslint-disable-line react-hooks/exhaustive-deps
  async function addAddress(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const payload=Object.fromEntries(["label","full_name","phone","country_code","city","region","postal_code","line1","line2"].map((key)=>[key,String(form.get(key)??"")]));try{await apiRequest("/auth/addresses/",{method:"POST",body:JSON.stringify({...payload,is_default:form.get("is_default")==="on"})});setMessage(en?"Address saved.":"تم حفظ العنوان.");formElement.reset();await load();}catch(error){setMessage(errorMessage(error));}}
  async function removeAddress(id:number){try{await apiRequest(`/auth/addresses/${id}/`,{method:"DELETE"});await load();}catch(error){setMessage(errorMessage(error));}}
  if(!user)return <main className="page container"><div className="empty-state"><h1>{en?"Sign in to manage your account":"سجّل الدخول لإدارة حسابك"}</h1><Link className="primary-button" href="/login">{en?"Sign in":"دخول"}</Link></div></main>;
  return <main className="page container"><div className="page-heading"><p className="eyebrow">{en?"Hello":"مرحبًا"} {user.full_name||user.username}</p><h1>{en?"My account and addresses":"حسابي وعناويني"}</h1><p>{user.email} · {user.phone}</p></div>{message&&<div className={message.includes("تم")||message.includes("saved")?"alert success":"alert error"}>{message}</div>}<div className="checkout-grid"><section><div className="panel"><h2>{en?"Saved addresses":"العناوين المحفوظة"}</h2>{addresses.map((address)=><div className="address-option" key={address.id}><b>{address.label} {address.is_default&&(en?"· Default":"· الافتراضي")}</b><p>{address.full_name} · {address.phone}<br/>{address.city}، {address.line1}</p><button className="danger-button" onClick={()=>void removeAddress(address.id)}>{en?"Remove":"حذف"}</button></div>)}</div><form className="form-card" onSubmit={addAddress}><h2>{en?"Add an address":"إضافة عنوان"}</h2><div className="form-grid">{[["label",en?"Label":"التسمية"],["full_name",en?"Full name":"الاسم الكامل"],["phone",en?"Phone":"الجوال"],["country_code",en?"Country code":"رمز الدولة"],["city",en?"City":"المدينة"],["region",en?"Region":"المنطقة"],["postal_code",en?"Postal code":"الرمز البريدي"],["line1",en?"Address":"العنوان"],["line2",en?"Additional details":"تفاصيل إضافية"]].map(([name,label])=><div className={`field ${["line1","line2"].includes(name)?"full":""}`} key={name}><label>{label}</label><input name={name} defaultValue={name==="label"?(en?"Home":"المنزل"):name==="full_name"?user.full_name:name==="phone"?user.phone:name==="country_code"?"SA":undefined} maxLength={name==="country_code"?2:undefined} required={["label","full_name","phone","country_code","city","line1"].includes(name)}/></div>)}<label className="field full"><span><input type="checkbox" name="is_default" style={{width:"auto"}}/> {en?"Make this my default address":"اجعله العنوان الافتراضي"}</span></label></div><button>{en?"Save address":"حفظ العنوان"}</button></form></section><aside className="panel"><h2>{en?"Notifications":"الإشعارات"}</h2>{notifications.map((notification)=><article className="review" key={notification.id}><h4>{notification.title}</h4><p>{notification.body}</p><small>{new Date(notification.created_at).toLocaleString(en?"en-US":"ar-SA")}</small></article>)}{!notifications.length&&<p>{en?"No notifications yet.":"لا توجد إشعارات بعد."}</p>}</aside></div></main>;
}
