"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

import { useStore } from "@/components/StoreProvider";
import { apiRequest, errorMessage } from "@/lib/client-api";
import type { Address, Paginated } from "@/lib/types";

type Notification = { id:number; title:string; body:string; is_read:boolean; created_at:string };
export default function AccountPage(){
  const {user}=useStore(); const [addresses,setAddresses]=useState<Address[]>([]); const [notifications,setNotifications]=useState<Notification[]>([]); const [message,setMessage]=useState("");
  async function load(){if(!user)return;const [addressPayload,notificationPayload]=await Promise.all([apiRequest<Address[]|Paginated<Address>>("/auth/addresses/"),apiRequest<Paginated<Notification>>("/notifications/")]);setAddresses(Array.isArray(addressPayload)?addressPayload:addressPayload.results);setNotifications(notificationPayload.results);}
  useEffect(()=>{void load();},[user]); // eslint-disable-line react-hooks/exhaustive-deps
  async function addAddress(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const payload=Object.fromEntries(["label","full_name","phone","country_code","city","region","postal_code","line1","line2"].map((key)=>[key,String(form.get(key)??"")]));try{await apiRequest("/auth/addresses/",{method:"POST",body:JSON.stringify({...payload,is_default:form.get("is_default")==="on"})});setMessage("تم حفظ العنوان.");formElement.reset();await load();}catch(error){setMessage(errorMessage(error));}}
  async function removeAddress(id:number){try{await apiRequest(`/auth/addresses/${id}/`,{method:"DELETE"});await load();}catch(error){setMessage(errorMessage(error));}}
  if(!user)return <main className="page container"><div className="empty-state"><h1>سجّل الدخول لإدارة حسابك</h1><Link className="primary-button" href="/login">دخول</Link></div></main>;
  return <main className="page container"><div className="page-heading"><p className="eyebrow">مرحبًا {user.full_name||user.username}</p><h1>حسابي وعناويني</h1><p>{user.email} · {user.phone}</p></div>{message&&<div className={message.includes("تم")?"alert success":"alert error"}>{message}</div>}<div className="checkout-grid"><section><div className="panel"><h2>العناوين المحفوظة</h2>{addresses.map((address)=><div className="address-option" key={address.id}><b>{address.label} {address.is_default&&"· الافتراضي"}</b><p>{address.full_name} · {address.phone}<br/>{address.city}، {address.line1}</p><button className="danger-button" onClick={()=>void removeAddress(address.id)}>حذف</button></div>)}</div><form className="form-card" onSubmit={addAddress}><h2>إضافة عنوان</h2><div className="form-grid"><div className="field"><label>التسمية</label><input name="label" defaultValue="المنزل" required/></div><div className="field"><label>الاسم الكامل</label><input name="full_name" defaultValue={user.full_name} required/></div><div className="field"><label>الجوال</label><input name="phone" defaultValue={user.phone} required/></div><div className="field"><label>رمز الدولة</label><input name="country_code" defaultValue="SA" maxLength={2} required/></div><div className="field"><label>المدينة</label><input name="city" required/></div><div className="field"><label>المنطقة</label><input name="region"/></div><div className="field"><label>الرمز البريدي</label><input name="postal_code"/></div><div className="field full"><label>العنوان</label><input name="line1" required/></div><div className="field full"><label>تفاصيل إضافية</label><input name="line2"/></div><label className="field full"><span><input type="checkbox" name="is_default" style={{width:"auto"}}/> اجعله العنوان الافتراضي</span></label></div><button>حفظ العنوان</button></form></section><aside className="panel"><h2>الإشعارات</h2>{notifications.map((notification)=><article className="review" key={notification.id}><h4>{notification.title}</h4><p>{notification.body}</p><small>{new Date(notification.created_at).toLocaleString("ar-SA")}</small></article>)}{!notifications.length&&<p>لا توجد إشعارات بعد.</p>}</aside></div></main>;
}
