# Generated by Django 5.2.16 on 2026-07-31 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'بانتظار المراجعة'), ('confirmed', 'تم التأكيد'), ('processing', 'قيد التجهيز'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='pending', max_length=30)),
                ('payment_status', models.CharField(choices=[('unpaid', 'غير مدفوع'), ('pending', 'قيد المعالجة'), ('paid', 'مدفوع'), ('failed', 'فشل الدفع'), ('refunded', 'مسترجع')], default='unpaid', max_length=30)),
                ('payment_method', models.CharField(choices=[('cod', 'الدفع عند الاستلام'), ('bank', 'تحويل بنكي')], default='cod', max_length=30)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('subtotal_cents', models.PositiveBigIntegerField(default=0)),
                ('shipping_cents', models.PositiveBigIntegerField(default=0)),
                ('total_cents', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_sku', models.CharField(max_length=60)),
                ('quantity', models.PositiveIntegerField()),
                ('price_cents', models.PositiveBigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
    ]
