# Generated by Django 5.2.16 on 2026-07-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage_productvariant_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_quantity',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='reorder_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
