# Generated by Django 5.2.16 on 2026-07-31 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_low_stock_threshold_product_reorder_quantity_and_more'),
        ('orders', '0002_order_address_line2_order_address_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsightReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('local', 'تحليل محلي'), ('openai', 'OpenAI')], max_length=20)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('period_days', models.PositiveSmallIntegerField(default=30)),
                ('summary', models.TextField()),
                ('priorities', models.JSONField(default=list)),
                ('opportunities', models.JSONField(default=list)),
                ('risks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_ai_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_cost_cents', models.PositiveBigIntegerField(default=0)),
                ('received_at', models.DateField()),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_batches', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_batches', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['expires_at', 'received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('out_of_stock', 'نفاد المخزون'), ('low_stock', 'مخزون منخفض'), ('expiring', 'قرب انتهاء الصلاحية'), ('expired', 'منتهي الصلاحية'), ('slow_moving', 'بطيء الحركة')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'معلومة'), ('warning', 'تحذير'), ('critical', 'حرج')], max_length=20)),
                ('fingerprint', models.CharField(max_length=180, unique=True)),
                ('message', models.CharField(max_length=350)),
                ('is_active', models.BooleanField(default=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_inventory_alerts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_alerts', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_alerts', to='catalog.productvariant')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='inventory.inventorybatch')),
            ],
            options={
                'ordering': ['-is_active', '-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opening', 'رصيد افتتاحي'), ('sale', 'بيع'), ('cancellation', 'إلغاء طلب'), ('restock', 'توريد'), ('adjustment', 'تسوية'), ('return', 'مرتجع'), ('expired', 'إتلاف منتهي')], max_length=30)),
                ('quantity_delta', models.IntegerField()),
                ('stock_after', models.PositiveIntegerField()),
                ('unit_cost_cents', models.PositiveBigIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.inventorybatch')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['expires_at', 'quantity'], name='inventory_i_expires_6d11bc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['product', 'variant', 'quantity'], name='inventory_i_product_628d78_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.UniqueConstraint(fields=('product', 'variant', 'lot_number'), name='unique_inventory_lot'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['is_active', 'severity', '-last_seen_at'], name='inventory_i_is_acti_84a4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['product', 'alert_type'], name='inventory_i_product_1e06b2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product', 'variant', '-created_at'], name='inventory_i_product_2044d8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['kind', '-created_at'], name='inventory_i_kind_cea733_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='inventory_movement_nonzero'),
        ),
    ]
